name: mousam
adopt-info: mousam
grade: stable
confinement: strict
base: core24
platforms:
  amd64:
  arm64:

parts:
  python-deps:
    source: .
    plugin: python
    python-packages:
      - requests==2.30.0
    prime:
      - -usr/bin/activate*
      - -usr/bin/Activate*
      - -usr/bin/pip*
      - -usr/bin/python*
      - -include
      - -lib
      - -lib64
      - -share
      - -pyvenv.cfg
    organize:
      lib/python3.12/site-packages: usr/lib/python3/dist-packages
      bin: usr/bin

  mousam:
    source: https://github.com/amit9838/mousam.git
    source-depth: 1
    #source-tag: used when there will be a new release with these fixes
    plugin: meson
    meson-parameters: [ --prefix=/snap/mousam/current/usr ]
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/mousam/current/usr/bin/mousam
    parse-info: [ usr/share/appdata/io.github.amit9838.mousam.appdata.xml ]
    organize:
      snap/mousam/current: .
    prime:
      - -snap/mousam

slots:
  mousam:
    interface: dbus
    bus: session
    name: io.github.amit9838.mousam

apps:
  mousam:
    command: usr/bin/mousam
    common-id: io.github.amit9838.mousam
    desktop: usr/share/applications/io.github.amit9838.mousam.desktop
    extensions: [ gnome ]
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - network
