from gettext import gettext as _

# --- Locations ---
ICON_LOC = "@icon_location@/share/icons/hicolor/scalable/mousam_icons/"

# --- Weather Icons ---
icons = {
    "0": ICON_LOC + "clear-day.svg",
    "1": ICON_LOC + "overcast-day.svg",
    "2": ICON_LOC + "overcast-day.svg",
    "3": ICON_LOC + "overcast.svg",
    "51": ICON_LOC + "partly-cloudy-day-drizzle.svg",
    "53": ICON_LOC + "drizzle.svg",
    "55": ICON_LOC + "overcast-drizzle.svg",
    "56": ICON_LOC + "partly-cloudy-day-snow.svg",
    "57": ICON_LOC + "overcast-snow.svg",
    "61": ICON_LOC + "partly-cloudy-day-rain.svg",
    "63": ICON_LOC + "rain.svg",
    "65": ICON_LOC + "thunderstorms-rain.svg",
    "66": ICON_LOC + "overcast-snow.svg",
    "67": ICON_LOC + "thunderstorms-rain.svg",
    "45": ICON_LOC + "fog.svg",
    "48": ICON_LOC + "fog.svg",
    "71": ICON_LOC + "partly-cloudy-day-snow.svg",
    "73": ICON_LOC + "snow.svg",
    "75": ICON_LOC + "snowflake.svg",
    "77": ICON_LOC + "snowflake.svg",
    "80": ICON_LOC + "overcast-day-rain.svg",
    "81": ICON_LOC + "rain.svg",
    "82": ICON_LOC + "thunderstorms-rain.svg",
    "85": ICON_LOC + "snow.svg",
    "86": ICON_LOC + "snowflake.svg",
    "95": ICON_LOC + "thunderstorms-rain.svg",
    "96": ICON_LOC + "thunderstorms-day-overcast-snow.svg",
    "99": ICON_LOC + "snowflake.svg",
    
    "0n": ICON_LOC + "clear-night.svg",
    "1n": ICON_LOC + "overcast-night.svg",
    "2n": ICON_LOC + "overcast-night.svg",
    "3n": ICON_LOC + "overcast.svg",
    "51n": ICON_LOC + "partly-cloudy-night-drizzle.svg",
    "53n": ICON_LOC + "drizzle.svg",
    "55n": ICON_LOC + "overcast-drizzle.svg",
    "56n": ICON_LOC + "partly-cloudy-night-snow.svg",
    "57n": ICON_LOC + "overcast-snow.svg",
    "61n": ICON_LOC + "partly-cloudy-night-rain.svg",
    "63n": ICON_LOC + "rain.svg",
    "65n": ICON_LOC + "thunderstorms-rain.svg",
    "66n": ICON_LOC + "overcast-snow.svg",
    "67n": ICON_LOC + "thunderstorms-rain.svg",
    "45n": ICON_LOC + "fog.svg",
    "48n": ICON_LOC + "fog.svg",
    "71n": ICON_LOC + "partly-cloudy-night-snow.svg",
    "73n": ICON_LOC + "snow.svg",
    "75n": ICON_LOC + "snowflake.svg",
    "77n": ICON_LOC + "snowflake.svg",
    "80n": ICON_LOC + "overcast-night-rain.svg",
    "81n": ICON_LOC + "rain.svg",
    "82n": ICON_LOC + "thunderstorms-rain.svg",
    "85n": ICON_LOC + "snow.svg",
    "86n": ICON_LOC + "snowflake.svg",
    "95n": ICON_LOC + "thunderstorms-rain.svg",
    "96n": ICON_LOC + "thunderstorms-night-overcast-snow.svg",
    "99n": ICON_LOC + "snowflake.svg",
    "arrow": ICON_LOC + "arrow.svg",
    "raindrop": ICON_LOC + "raindrop.svg",
    "raindrops": ICON_LOC + "raindrops.svg",
    "wind": ICON_LOC + "wind.svg",
}

# --- Background CSS ---
bg_css = {
    "0": "bg-weather-clear-sky",
    "1": "bg-weather-few-clouds",
    "2": "bg-weather-few-clouds",
    "3": "bg-weather-overcast",
    "51": "bg-weather-showers-scattered",
    "53": "bg-weather-showers-scattered",
    "55": "bg-weather-showers-scattered",
    "56": "bg-weather-snow",
    "57": "bg-weather-snow",
    "61": "bg-weather-showers-scattered",
    "63": "bg-weather-showers-large",
    "65": "bg-weather-showers-large",
    "66": "bg-weather-snow",
    "67": "bg-weather-showers-large",
    "45": "bg-weather-fog",
    "48": "bg-weather-fog",
    "71": "bg-weather-snow",
    "73": "bg-weather-snow",
    "75": "bg-weather-snow",
    "77": "bg-weather-snow",
    "80": "bg-weather-showers-large",
    "81": "bg-weather-showers-large",
    "82": "bg-weather-showers-large",
    "85": "bg-weather-snow",
    "86": "bg-weather-snow",
    "95": "bg-weather-storm",
    "96": "bg-weather-storm",
    "99": "bg-weather-snow",

    "0n": "bg-weather-clear-sky-night",
    "1n": "bg-weather-few-clouds-night",
    "2n": "bg-weather-few-clouds-night",
    "3n": "bg-weather-overcast-night",
    "51n": "bg-weather-showers-scattered-night",
    "53n": "bg-weather-showers-scattered-night",
    "55n": "bg-weather-showers-scattered-night",
    "56n": "bg-weather-snow-night",
    "57n": "bg-weather-snow-night",
    "61n": "bg-weather-showers-scattered-night",
    "63n": "bg-weather-showers-large-night",
    "65n": "bg-weather-showers-large-night",
    "66n": "bg-weather-snow-night",
    "67n": "bg-weather-showers-large-night",
    "45n": "bg-weather-fog-night",
    "48n": "bg-weather-fog-night",
    "71n": "bg-weather-snow-night",
    "73n": "bg-weather-snow-night",
    "75n": "bg-weather-snow-night",
    "77n": "bg-weather-snow-night",
    "80n": "bg-weather-showers-large-night",
    "81n": "bg-weather-showers-large-night",
    "82n": "bg-weather-showers-large-night",
    "85n": "bg-weather-snow-night",
    "86n": "bg-weather-snow-night",
    "95n": "bg-weather-storm-night",
    "96n": "bg-weather-storm-night",
    "99n": "bg-weather-snow-night",
}

# --- Weather Conditions ---
condition = {
    "0": _("Clear sky"),
    "1": _("Few Clouds"),
    "2": _("Partly Cloudy"),
    "3": _("Overcast"),
    "45": _("Fog"),
    "48": _("Mist"),
    "51": _("Light Drizzle"),
    "53": _("Moderate Drizzle"),
    "55": _("Heavy Intensity Drizzle"),
    "56": _("Light Freezing Drizzle"),
    "57": _("Heavy Freezing Drizzle"),
    "61": _("Light Rain"),
    "63": _("Moderate Rain"),
    "65": _("Heavy Rain"),
    "66": _("Light Freezing Rain"),
    "67": _("Heavy Freezing Rain"),
    "71": _("Light Snow Fall"),
    "73": _("Moderate Snow Fall"),
    "75": _("Heavy Snow Fall"),
    "77": _("Snow grains"),
    "80": _("Light Rain Showers"),
    "81": _("Moderate Rain Showers"),
    "82": _("Heavy Rain Showers"),
    "85": _("Light Snow Showers"),
    "86": _("Heavy Snow Showers "),
    "95": _("Thunderstorm"),
    "96": _("Thunderstorm with Hail"),
}
