name: mousam
adopt-info: mousam

grade: stable
confinement: strict

base: core22
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  mousam:
    source: https://github.com/amit9838/weather.git
    source-depth: 1
    #source-tag: used when there will be a new release with these fixes
    plugin: meson
    meson-parameters: [ --prefix=/snap/mousam/current/usr ]
    override-pull: |
      craftctl default
      pip install --prefix=$CRAFT_PART_INSTALL/usr requests==2.30.0
    override-build: |
      craftctl default
      chmod +x $CRAFT_PART_INSTALL/snap/mousam/current/usr/bin/weather
      sed -e '1c#!/usr/bin/python3' -i $CRAFT_PART_INSTALL/usr/local/bin/*
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/mousam/current/usr/bin/weather
    parse-info: [ usr/share/appdata/io.github.amit9838.weather.appdata.xml ]
    organize:
      snap/mousam/current: .
      usr/local: usr
      usr/lib/python3: usr/lib/python3.10
    prime:
      - -snap/mousam

slots:
  mousam:
    interface: dbus
    bus: session
    name: io.github.amit9838.weather

apps:
  mousam:
    command: usr/bin/weather
    common-id: io.github.amit9838.weather
    desktop: usr/share/applications/io.github.amit9838.weather.desktop
    extensions: [ gnome ]
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.10/dist-packages:$PYTHONPATH
    plugs:
      - network
